# Generated by Django 5.2.5 on 2025-08-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_author_blog_entry_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
